name: RenameItems
main: Wertzui123\RenameItems\Main
version: 2.0
api: 3.0.0
load: POSTWORLD
author: Wertzui123
description: A simple rename plugin by Wertzui123
website: https://github.com/Wertzui123/RenameItems
permissions:
 renameitems:
  default: false
  description: Let you use all features of RenameItems
  children:
   renameitems.cmd.rename:
    default: op
    description: Permission for /rename
   renameitems.cmd.block:
    default: false
    description: Permission for /block
   renameitems.blockeditems.bypass:
    default: false
    description: Permission for renaming blocked items