name: RenameItems
main: Wertzui123\RenameItems\Main
version: 1.0
api: 3.0.0
load: POSTWORLD
author: Wertzui123
description: A simple rename plugin by Wertzui123
website: https://github.com/Wertzui123/RenameItems
permissions:
 renameitems:
  default: op
  description: Let you use all features of RenameItems
  children:
   renameitems.rename.cmd:
    default: op
    description: Allows the use of /rename
   renameitems.blockeditems.bypass:
    default: false
    description: Allows the use of renaming items wich are blocked
